-- V34__external_integration.sql
-- 美研云门店中台 - 域⑧平台基建：外部依赖统一配置窗口（P5-B57 卡2）
-- 版本号：全库共享 flyway_schema_history 全局递增，V33（finance 报告验真）之后首个空号 V34。
-- 属主：org-service（第 9 个接入 Flyway 的服务，配置照抄 ai-service 共享链：
--   baseline-version=0 + ignore *:missing/*:future）。
-- 幂等：CREATE TABLE IF NOT EXISTS + 目录行 INSERT ... ON CONFLICT DO NOTHING；
--   不 ALTER 任何存量表；全新库/正式库/种子库同脚本执行。

CREATE TABLE IF NOT EXISTS external_integration (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    integration_code  VARCHAR(64)  NOT NULL,
    category          VARCHAR(32)  NOT NULL,            -- NOTIFY_GATEWAY / AD_CHANNEL
    integration_name  VARCHAR(128) NOT NULL,            -- 中文展示名
    value_kind        VARCHAR(16)  NOT NULL,            -- URL / SECRET / SWITCH
    base_url          VARCHAR(512),                     -- URL 类：网关 webhook
    secret_cipher     TEXT,                             -- SECRET 类：AES-GCM 密文（org 单点持钥）
    secret_mask       VARCHAR(80),                      -- 掩码回显（前4****后4），明文绝不下发
    bool_value        BOOLEAN,                          -- SWITCH 类：开关实际值
    enabled           BOOLEAN      NOT NULL DEFAULT FALSE, -- 录入并启用后才被消费侧取用
    config_json       JSONB,                            -- 协议扩展位（P1 verifyMode 等），P0 可空
    remark            VARCHAR(256),                     -- 「未配置影响」诚实文案
    last_test_at      TIMESTAMPTZ,
    last_test_ok      BOOLEAN,
    last_test_msg     VARCHAR(256),
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by        VARCHAR(64),
    CONSTRAINT uq_external_integration_code UNIQUE (integration_code),
    CONSTRAINT ck_external_integration_kind CHECK (value_kind IN ('URL','SECRET','SWITCH'))
);
COMMENT ON TABLE external_integration IS '外部依赖统一配置窗口（P5-B57）：通知网关/广告渠道密钥/安全开关，org-service 平台属主';

-- P0 目录行（固定 7 项，ON CONFLICT 幂等；代码侧 IntegrationCatalog 同口径枚举，禁止前端自由建项）
INSERT INTO external_integration
    (integration_code, category, integration_name, value_kind, enabled, bool_value, remark)
VALUES
    ('NOTIFY_SMS_GATEWAY',   'NOTIFY_GATEWAY', '短信通知网关 webhook', 'URL', FALSE, NULL,
     '未配置：短信通道跳过（SKIPPED），通知仅站内信送达，不产生真实短信'),
    ('NOTIFY_WECHAT_GATEWAY','NOTIFY_GATEWAY', '企业微信通知 webhook', 'URL', FALSE, NULL,
     '未配置：企微通道跳过（SKIPPED），通知仅站内信送达'),
    ('NOTIFY_EMAIL_GATEWAY', 'NOTIFY_GATEWAY', '邮件通知网关 webhook', 'URL', FALSE, NULL,
     '未配置：邮件通道跳过（SKIPPED），通知仅站内信送达'),
    ('AD_SECRET_DOUYIN',     'AD_CHANNEL',     '抖音/巨量回传签名密钥', 'SECRET', FALSE, NULL,
     '未配置：抖音回传一律 503 拒绝（fail-closed，杜绝伪造转化）'),
    ('AD_SECRET_RED',        'AD_CHANNEL',     '小红书回传签名密钥', 'SECRET', FALSE, NULL,
     '未配置：小红书回传一律 503 拒绝'),
    ('AD_SECRET_MEITUAN',    'AD_CHANNEL',     '美团回传签名密钥', 'SECRET', FALSE, NULL,
     '未配置：美团回传一律 503 拒绝'),
    ('AD_DEV_NO_AUTH',       'AD_CHANNEL',     '广告回传免签（仅联调）', 'SWITCH', FALSE, FALSE,
     '关闭（默认）：回传必须验签；开启仅限联调环境，生产开启视同安全事故，启动与保存均告警')
ON CONFLICT (integration_code) DO NOTHING;
